// If you finish this kata, you can try Insane Coloured Triangles by Bubbler, which is a much harder version of this one.

// A coloured triangle is created from a row of colours, each of which is red, green or blue. Successive rows, each containing one fewer colour than the last, are generated by considering the two touching colours in the previous row. If these colours are identical, the same colour is used in the new row. If they are different, the missing colour is used in the new row. This is continued until the final row, with only a single colour, is generated.

// The different possibilities are:

// Colour here:        G G        B G        R G        B R
// Becomes colour:      G          R          B          G
// With a bigger example:

// R R G B R G B B
//  R B R G B R B
//   G G B R G G
//    G R G B G
//     B B R R
//      B G R
//       R B
//        G
// You will be given the first row of the triangle as a string and its your job to return the final colour which would appear in the bottom row as a string. In the case of the example above, you would the given RRGBRGBB you should return G.

// The input string will only contain the uppercase letters R, G, B and there will be at least one letter so you do not have to test for invalid input.
// If you are only given one colour as the input, return that colour.
// Adapted from the 2017 British Informatics Olympiad


// PREP
// Parameters:
// We are given a string of uppercase letters of either "R, G, B"
// Results:
// We are to return a single letter, generated by the following patterns
// the length of the string, or array if we turn it into one, decreases by one each time, and the values of the array comes from the array before it. if the two letters are the same, else it is to be the missing one.
// Example:
// "RGBRGB"
//  "BRGBR"
//   "GBRG"
//    "RGB"
//     "BR"
//      "G"
// then we retun "G"

// Pseudocode:
// we will make intermediary arrays, and decrease the length by one following this formula. 
// I am need of a new plan. 
// I am wanting to find a way to re-run the new array through the converting code, but it seems the row array is not getting shorter, the way I expected. I am running into problems with using the while loop as well as the for loop and a resetting by using i -= 1.
// 


// function triangle(row) {
//     row = row.split('')
//     let newRow = []
//     console.log(row.length)
//     for(let i = 0; i < row.length; i++){
      
//         if(row[0] === row[1]){
//             newRow.push(row[0])
//             row.shift()
//             console.log(newRow, row, i)
//             i -= 1

//         }else if(row[0] !== row[1]){
//             console.log("row=", row, "i=",i)
//             if(row[0] !== "R" && row[1] !== "R"){
//                 newRow.push("R")
//             }else if(row[0] !== "G" && row[1] !== "G"){
//                 newRow.push("G")
//             }else if(row[0] !== "B" && row[1] !== "B"){
//                 newRow.push("B")
//             }
//             row.shift()
//             // console.log("row=",row, "newRow=", newRow)
//             i -= 1
//         }
       
//     }
//     return newRow
//     // Return the answer
//     }
//     console.log(triangle('RBRGBRBGGRRRBGBBBGG'))


    function triangle(row) {
        if(row.length === 1){
            return row
        }
        row = row.split('')
        let newRow = []
        while(row.length > 1){
            if(row[0] === row[1]){
                newRow.push(row[0])
                row.shift()
            }else if(row[0] !== row[1]){
                console.log("row=", row)
                if(row[0] !== "R" && row[1] !== "R"){
                    newRow.push("R")
                    row.shift()
                }else if(row[0] !== "G" && row[1] !== "G"){
                    newRow.push("G")
                    row.shift()
                }else if(row[0] !== "B" && row[1] !== "B"){
                    newRow.push("B")
                    row.shift()
                }
                   
            }
         
                if(row.length === 1){
                    row = newRow
                }   
        
    }
    return newRow
}

console.log(triangle('RBRGBRBGGRRRBGBBBGG'))
