// If you finish this kata, you can try Insane Coloured Triangles by Bubbler, which is a much harder version of this one.

// A coloured triangle is created from a row of colours, each of which is red, green or blue. Successive rows, each containing one fewer colour than the last, are generated by considering the two touching colours in the previous row. If these colours are identical, the same colour is used in the new row. If they are different, the missing colour is used in the new row. This is continued until the final row, with only a single colour, is generated.

// The different possibilities are:

// Colour here:        G G        B G        R G        B R
// Becomes colour:      G          R          B          G
// With a bigger example:

// R R G B R G B B
//  R B R G B R B
//   G G B R G G
//    G R G B G
//     B B R R
//      B G R
//       R B
//        G
// You will be given the first row of the triangle as a string and its your job to return the final colour which would appear in the bottom row as a string. In the case of the example above, you would the given RRGBRGBB you should return G.

// The input string will only contain the uppercase letters R, G, B and there will be at least one letter so you do not have to test for invalid input.
// If you are only given one colour as the input, return that colour.
// Adapted from the 2017 British Informatics Olympiad


// const Test = require('@codewars/test-compat');

// describe("Tests", () => {
//   it("test", () => {
// Test.assertEquals(triangle('GB'), 'R');
// Test.assertEquals(triangle('RRR'), 'R');
// Test.assertEquals(triangle('RGBG'), 'B');
// Test.assertEquals(triangle('RBRGBRB'), 'G');
// Test.assertEquals(triangle('RBRGBRBGGRRRBGBBBGG'), 'G');
// Test.assertEquals(triangle('B'), 'B');
//   });
// });


// pseudocode:
// need to compare two values and add a third value to a return string

// need to pass the result in again til you get to one

function triangle(row) {
    if(row.length === 1) return row
    let arr = row.split("")
    let str = []

    while(arr.length >= 1){
    for(let i = 0; i < arr.length; i ++){

        if(arr.length === 1){
            return arr.join('')
        }else if(arr[i] === 'R' && arr[i+1] === 'R'){
            str.push('R')
        }else if(arr[i] === 'R' && arr[i+1] === 'B'){
            str.push('G')
        }else if(arr[i] === 'R' && arr[i+1] === 'G'){
            str.push('B')
        }else if(arr[i] === 'B' && arr[i+1] === 'B'){
            str.push('B')
        }else if(arr[i] === 'B' && arr[i+1] === 'R'){
            str.push('G')
        }else if(arr[i] === 'B' && arr[i+1] === 'G'){
            str.push('R')
        }else if(arr[i] === 'G' && arr[i+1] === 'G'){
            str.push('G')
        }else if(arr[i] === 'G' && arr[i+1] === 'B'){
            str.push('R')
        }else if(arr[i] === 'G' && arr[i+1] === 'R'){
            str.push('B')
        }
    }
        arr = str
        str = []
        
} 
        
        
    }

    console.log(triangle('RBRGBRBGGRRRBGBBBGG'))